name: mock_project
description: Mock Project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.1
  dio: ^5.0.0
  http: ^0.13.5
  global_configs: ^1.1.2
  global_configuration: ^2.0.0-nullsafety.1
  get_it: ^7.2.0
  auto_route: ^5.0.4
  hive: ^2.2.3
  line_icons: ^2.0.0
  json_serializable: ^6.6.1
  json_annotation: ^4.8.0
  basic_utils: ^5.5.1
  flutter_bloc: ^8.1.2
  fluttertoast: ^8.2.1
  responsive_framework: ^0.2.0
  freezed_annotation: ^2.2.0
  flutter_lints: ^2.0.1
  after_layout: ^1.2.0
  equatable: ^2.0.5

  battery:
    git:
      url: https://truongluan998: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@github.com/truongluan998/battery-plugin.git
      ref: main
      path: battery/

  connectivity:
    git:
      url: https://truongluan998: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@github.com/truongluan998/connectivity-plugin.git
      ref: main
      path: connectivity/

  rest_utils:
    git:
      url: https://truongluan998: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@github.com/truongluan998/rest-utils-plugin.git
      ref: main
      path: rest_utils/

  #Firebase
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  cloud_firestore: ^4.4.3
  firebase_analytics: ^10.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  auto_route_generator:
  flutter_native_splash: ^2.2.16
  flutter_launcher_icons: ^0.11.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/app_logo.png
  web: false

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/cfg/
    - assets/images/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-VariableFont_wght.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
        - asset: assets/fonts/Quicksand-Light.ttf
        - asset: assets/fonts/Quicksand-Medium.ttf
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-SemiBold.ttf
