// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVwDhKDIZ3NjFbqdMOrSYdC3fWOrs6YLY',
    appId: '1:73800511217:web:db1b1e3d2fa9a6f9284350',
    messagingSenderId: '73800511217',
    projectId: 'chatgpt-19a02',
    authDomain: 'chatgpt-19a02.firebaseapp.com',
    storageBucket: 'chatgpt-19a02.appspot.com',
    measurementId: 'G-EN53SEG9YV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM_LHbyla4wlq1-xBI4x3XVp0WDBgLyFI',
    appId: '1:73800511217:android:f3023febd3154667284350',
    messagingSenderId: '73800511217',
    projectId: 'chatgpt-19a02',
    storageBucket: 'chatgpt-19a02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwkR-79-P_iUOfV6GDfR6DrRs8YcbY-Jg',
    appId: '1:73800511217:ios:c9e542ddb424b116284350',
    messagingSenderId: '73800511217',
    projectId: 'chatgpt-19a02',
    storageBucket: 'chatgpt-19a02.appspot.com',
    iosClientId: '73800511217-93dp5ggil0dphn9b70583vs7jig76k97.apps.googleusercontent.com',
    iosBundleId: 'com.example.mockProject',
  );
}
