name: Chat GPT CI + CD
on:
  pull_request:
    brand:
      - develop
jobs:
  android_build:
    name: Build ChatGPT
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Build Android
        uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: stable
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v3
        with:
          name: release-android-app
          path: build/app/outputs/flutter-apk/app-release.apk
      - name: Install @actions/artifact
        run: npm install @actions/artifact
      
      - name: Get artifacts download URL
        id: download_url
        run: |
          mkdir artifacts
          cd artifacts
          # Download the artifact using the actions/download-artifact@v2 action
          npx @actions/artifact download -n release-android-app -r ${{ github.repository }} -c ${{ github.ref }} -d .
          # Get the download URL for the artifact
          echo "::set-output name=url::$(node -e 'console.log(require(`./release-android-app`).archive_download_url)')"

      
      - uses: dawidd6/action-send-mail@v2
        if: always()
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ${{ github.repository }} ${{ github.job }} is ${{ job.status }}
          body: |
            ${{ github.job }} job in workflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
            Link: ${{ steps.download_url.outputs.url }}
          to: truongluan998@gmail.com, binhp1999@gmail.com
          from: ChatGPT  
