name: Chat GPT CI + CD
on:
  pull_request:
    brand:
      - develop
jobs:
  code-analysis-and-testing:
    if: false
    name: Code analysis and testing
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: stable
      - name: Get pub dependencies
        run: flutter pub get
      - name: Flutter analyze
        run: flutter analyze
      - name: Flutter test
        run: flutter test

  chatgot_build:
    name: Build ChatGPT
    needs: code-analysis-and-testing.result == 'success'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Build Android
        uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: stable
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v3
        with:
          name: release-android-app
          path: build/app/outputs/flutter-apk/app-release.apk
      - uses: dawidd6/action-send-mail@v2
        if: always()
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ${{ github.repository }} ${{ github.job }} is ${{ job.status }}
          body: 'Build complete'
          to: truongluan998@gmail.com, binhp1999@gmail.com
          from: ChatGPT
